###

GET http://localhost:3000/todos/?status=TO%20DO

###

GET http://localhost:3000/todos/?priority=HIGH&status=IN%20PROGRESS

###

GET http://localhost:3000/todos/?category=WORK&status=IN%20PROGRESS

###
GET http://localhost:3000/todos/5
###

GET http://localhost:3000/agenda/?date=2021-24-04
###

POST http://localhost:3000/todos/
Content-Type: application/json

{
  
    "id": 11,
    "todo": "Get the Job",
    "priority": "HIGH",
    "category": "Goal",
    "status": "IN PROGRESS",
    "dueDate": "2021-05-11"
  }

###

PUT http://localhost:3000/todos/1/
Content-Type: application/json

{
  "dueDate": "2012-12-22"

}
###

DELETE http://localhost:3000/todos/2