###

GET http://localhost:3000/todos/?status=TO%20DO

###

GET http://localhost:3000/todos/?priority=HIGH&status=IN%20PROGRESS

###

GET http://localhost:3000/todos/?category=WORK&status=DONE

###
GET http://localhost:3000/todos/?search_q=Buy

###
GET http://localhost:3000/todos/?category=WORK&status=IN%20PROGRESS

###
GET http://localhost:3000/todos/111
###

GET http://localhost:3000/agenda/?date=2021-05-11754
###

POST http://localhost:3000/todos/
Content-Type: application/json

{
  
    "id": 1111,
    "todo": "Hai",
    "priority": "HIGH",
    "category": "WORK",
    "status": "IN PROGRESS",
    "dueDate": "2021-05-11"
  }

###

PUT http://localhost:3000/todos/111/
Content-Type: application/json

{
  "dueDate": "2021-06-11"
}
###

DELETE http://localhost:3000/todos/11